- dbffilewriter/pom.xml
- dbffilewriter/src/main/java/com/alibaba/datax/plugin/writer/dbffilewriter/DbfFileWriter.java
- docs/dbffilewriter.md
> bugfix: dbf which wroten can not read

- CHANGELOG.md
- oraclewriter/src/main/java/com/alibaba/datax/plugin/writer/oraclewriter/OracleWriter.java
- plugin-rdbms-util/src/main/java/com/alibaba/datax/plugin/rdbms/writer/CommonRdbmsWriter.java
- plugin-rdbms-util/src/main/java/com/alibaba/datax/plugin/rdbms/writer/Key.java
- plugin-rdbms-util/src/main/java/com/alibaba/datax/plugin/rdbms/writer/util/WriterUtil.java
Support oracle merge statement(#82)
> Support oracle merge statement

- docs/src/main/sphinx/writer/postgresqlwriter.md
- plugin-rdbms-util/src/main/java/com/alibaba/datax/plugin/rdbms/writer/util/WriterUtil.java
- postgresqlwriter/src/main/java/com/alibaba/datax/plugin/writer/postgresqlwriter/PostgresqlWriter.java
Add support for PostgresSQL update statement (#82)
> Add support for postgresql update statement

- core/src/main/job/stream2kudu.json
- docs/src/main/sphinx/kuduwriter/kuduwirter.md
- kudureader/src/main/resources/plugin_job_template.json
- kuduwriter/package.xml
- kuduwriter/pom.xml
- kuduwriter/src/main/java/com/alibaba/datax/plugin/writer/kuduwriter/ColumnType.java
- kuduwriter/src/main/java/com/alibaba/datax/plugin/writer/kuduwriter/Constant.java
- kuduwriter/src/main/java/com/alibaba/datax/plugin/writer/kuduwriter/InsertModeType.java
- kuduwriter/src/main/java/com/alibaba/datax/plugin/writer/kuduwriter/Key.java
- kuduwriter/src/main/java/com/alibaba/datax/plugin/writer/kuduwriter/KuduHelper.java
- kuduwriter/src/main/java/com/alibaba/datax/plugin/writer/kuduwriter/KuduWriter.java
- kuduwriter/src/main/java/com/alibaba/datax/plugin/writer/kuduwriter/KuduWriterErrorCode.java
- kuduwriter/src/main/java/com/alibaba/datax/plugin/writer/kuduwriter/KuduWriterTask.java
- kuduwriter/src/main/resources/plugin.json
- kuduwriter/src/main/resources/plugin_job_template.json
- pom.xml
> Kudu writer

- core/src/main/job/stream2gp.json
- docs/src/main/sphinx/writer/greenplumwriter.md
- greenplumwriter/package.xml
- greenplumwriter/pom.xml
- greenplumwriter/src/main/java/com/alibaba/datax/plugin/writer/greenplumwriter/Constant.java
- greenplumwriter/src/main/java/com/alibaba/datax/plugin/writer/greenplumwriter/CopyProcessor.java
- greenplumwriter/src/main/java/com/alibaba/datax/plugin/writer/greenplumwriter/CopyWorker.java
- greenplumwriter/src/main/java/com/alibaba/datax/plugin/writer/greenplumwriter/CopyWriterTask.java
- greenplumwriter/src/main/java/com/alibaba/datax/plugin/writer/greenplumwriter/GreenplumWriter.java
- greenplumwriter/src/main/java/com/alibaba/datax/plugin/writer/greenplumwriter/Key.java
- greenplumwriter/src/main/resources/plugin.json
- greenplumwriter/src/main/resources/plugin_job_template.json
- pom.xml
Add Greenplum writer plugin #96
> Add Greenplum writer plugin

- README.md
- core/src/main/job/influxdb2pg.json
- core/src/main/job/influxdb2stream.json
- docs/src/main/sphinx/reader/influxdbreader.md
- influxdbreader/package.xml
- influxdbreader/pom.xml
- influxdbreader/src/main/java/com/alibaba/datax/plugin/reader/influxdbreader/InfluxDBReader.java
- influxdbreader/src/main/java/com/alibaba/datax/plugin/reader/influxdbreader/InfluxDBReaderErrorCode.java
- influxdbreader/src/main/java/com/alibaba/datax/plugin/reader/influxdbreader/InfluxDBReaderTask.java
- influxdbreader/src/main/java/com/alibaba/datax/plugin/reader/influxdbreader/Key.java
- influxdbreader/src/main/resources/plugin.json
- influxdbreader/src/main/resources/plugin_job_template.json
- mysqlreader/src/main/java/com/alibaba/datax/plugin/reader/influxdbreader/MysqlReader.java
- mysqlreader/src/main/java/com/alibaba/datax/plugin/reader/influxdbreader/MysqlReaderErrorCode.java
- plugin-rdbms-util/src/main/java/com/alibaba/datax/plugin/rdbms/util/DataBaseType.java
- pom.xml
Add InfluxDB reader plugin #96
> Add InfluxDB reader plugin

- plugin/writer/influxdbwriter/src/main/java/com/wgzhao/datax/plugin/writer/influxdbwriter/InfluxDBWriter.java
> Add support for more than one channel setup

- docs/src/main/sphinx/writer/doriswriter.md
- plugin/writer/doriswriter/package.xml
- plugin/writer/doriswriter/pom.xml
- plugin/writer/doriswriter/src/main/java/com/wgzhao/datax/plugin/writer/doriswriter/DorisWriter.java
- plugin/writer/doriswriter/src/main/java/com/wgzhao/datax/plugin/writer/doriswriter/DorisWriterErrorCode.java
- plugin/writer/doriswriter/src/main/java/com/wgzhao/datax/plugin/writer/doriswriter/DorisWriterTask.java
- plugin/writer/doriswriter/src/main/java/com/wgzhao/datax/plugin/writer/doriswriter/Key.java
- plugin/writer/doriswriter/src/main/resources/plugin.json
- plugin/writer/doriswriter/src/main/resources/plugin_job_template.json
- pom.xml
> Add support for DorisDB writer

- plugin/writer/hdfswriter/src/main/java/com/wgzhao/datax/plugin/writer/hdfswriter/HdfsHelper.java
Fixed: Unknow host exception when writing parquet file
> Fixed: Unknow host exception when writing parquet file

- deploy_zip.sh
- docs/src/main/sphinx/reader/txtfilereader.md
- plugin/reader/txtfilereader/pom.xml
- plugin/reader/txtfilereader/src/main/java/com/wgzhao/datax/plugin/reader/txtfilereader/Constant.java
- plugin/reader/txtfilereader/src/main/java/com/wgzhao/datax/plugin/reader/txtfilereader/FileHelper.java
- plugin/reader/txtfilereader/src/main/java/com/wgzhao/datax/plugin/reader/txtfilereader/Key.java
- plugin/reader/txtfilereader/src/main/java/com/wgzhao/datax/plugin/reader/txtfilereader/TxtFileReader.java
- plugin/reader/txtfilereader/src/main/java/com/wgzhao/datax/plugin/reader/txtfilereader/TxtFileReaderErrorCode.java
- plugin/reader/txtfilereader/src/main/java/com/wgzhao/datax/plugin/reader/txtfilereader/ZipCycleInputStream.java
1. Remove dependency of  `plugin-storage-util` fixed #149 
2. Add support for more compress format
3. Allow mixed compress format in specified folder
> plugin txtfilereader support more compress format

- plugin/writer/influxdbwriter/src/main/java/com/wgzhao/datax/plugin/writer/influxdbwriter/InfluxDBWriterTask.java
1. 可能源数据没有time列，或者time列不在第一个，所以需要此MR的处理方式予以处理
2. 在初始化的时候ping服务器（用于某些时候调试问题）
3. 将TAG的设置放到switch type里。
> influxdb: fix column maybe not have time

- common/src/main/java/com/wgzhao/addax/common/util/RecordUtil.java
- plugin/reader/dbffilereader/pom.xml
- plugin/reader/dbffilereader/src/main/java/com/wgzhao/addax/plugin/reader/dbffilereader/DbfFileReader.java
- plugin/writer/dbffilewriter/pom.xml
- plugin/writer/dbffilewriter/src/main/java/com/wgzhao/addax/plugin/writer/dbffilewriter/DbfFileWriter.java
- plugin/writer/dbffilewriter/src/test/java/com/wgzhao/addax/plugin/writer/dbffilewriter/TestDbf.java
Fixed null pointer exception when reading null value #229
> Fixed null pointer exception when reading null value #229

- plugin-rdbms-util/src/main/java/com/wgzhao/addax/plugin/rdbms/util/DBUtil.java
- plugin/reader/rdbmsreader/src/main/resources/plugin.json
Add missing driver class name to `plugin.json`
> rdbms reader can not load correct jdbc driver #232

- plugin/reader/dbffilereader/src/main/java/com/wgzhao/addax/plugin/reader/dbffilereader/DbfFileReader.java
In `dbffilereader` plugin, You can set the `column` configuration item to `["*"]` to indicate that all fields of the dbf file are read and the data type is automatically determined
> Add support for wildcard to column item

- plugin/writer/hbase20xsqlwriter/pom.xml
- plugin/writer/hbase20xsqlwriter/src/main/java/com/wgzhao/addax/plugin/writer/hbase20xsqlwriter/HBase20xSQLHelper.java
- plugin/writer/hbase20xsqlwriter/src/main/java/com/wgzhao/addax/plugin/writer/hbase20xsqlwriter/HBase20xSQLWriterErrorCode.java
- plugin/writer/hbase20xsqlwriter/src/main/java/com/wgzhao/addax/plugin/writer/hbase20xsqlwriter/HBase20xSQLWriterTask.java
- plugin/writer/hbase20xsqlwriter/src/main/resources/plugin_job_template.json
1. Add support for kerberos authentication.
2. Add support for phoenix thick connection mode
3. Use Phoenix offical maven repo
> Add support for kerberos authentication and phoenix thick connection mode

- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/util/DBUtil.java
Fixed load empty jdbc driver class #255
> Fixed load empty jdbc driver class

- Dockerfile
- README.md
- README_zh.md
- core/src/main/bin/addax.sh
- shrink_package.sh
> Add support for docker

- plugin/reader/tdenginereader/src/main/java/com/wgzhao/addax/plugin/reader/tdenginereader/TDengineReader.java
Fix null pointer exception when not setting fetchSize item #270
> Fix null pointer exception when not setting fetchSize item #270

- plugin/writer/kuduwriter/src/main/java/com/wgzhao/addax/plugin/writer/kuduwriter/KuduWriterTask.java
Refer to #294  for more detail
> [kuduwriter] Fix data lost without flushing cache #294

- docs/src/main/sphinx/reader/kudureader.md
- plugin/reader/kudureader/src/main/java/com/wgzhao/addax/plugin/reader/kudureader/KuduReader.java
- plugin/reader/kudureader/src/main/resources/plugin_job_template.json
Allow specify columns instead of all columns #252, #295
> [kudureader] Allow specify columns instead of all columns

- docs/src/main/sphinx/reader/kudureader.md
- plugin/reader/kudureader/src/main/java/com/wgzhao/addax/plugin/reader/kudureader/KuduReader.java
[kudureader] Add support for configuring `where` to set more filters #252, #292
> [kudureader] Add support for configuring `where` to set more filters

- lib/addax-storage/pom.xml
- plugin/reader/dbfreader/pom.xml
- plugin/reader/hbase11xreader/pom.xml
- plugin/reader/hbase11xsqlreader/pom.xml
- plugin/reader/txtfilereader/pom.xml
- plugin/writer/hbase11xsqlwriter/pom.xml
- plugin/writer/kuduwriter/pom.xml
- pom.xml
> [general] Enable maven enforce plugin

- common/src/main/java/com/wgzhao/addax/common/element/BoolColumn.java
- common/src/main/java/com/wgzhao/addax/common/element/BytesColumn.java
- common/src/main/java/com/wgzhao/addax/common/element/Column.java
- common/src/main/java/com/wgzhao/addax/common/element/DateColumn.java
- common/src/main/java/com/wgzhao/addax/common/element/DoubleColumn.java
- common/src/main/java/com/wgzhao/addax/common/element/LongColumn.java
- common/src/main/java/com/wgzhao/addax/common/element/StringColumn.java
- common/src/main/java/com/wgzhao/addax/common/element/TimestampColumn.java
- core/src/main/java/com/wgzhao/addax/core/statistics/plugin/task/util/DirtyRecord.java
- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/reader/CommonRdbmsReader.java
- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/writer/CommonRdbmsWriter.java
- plugin/reader/streamreader/src/main/java/com/wgzhao/addax/plugin/reader/streamreader/StreamReader.java
> [common] Add internal TIMESTAMP data type for higher precision

- docs/reader/httpreader.md
- plugin/reader/httpreader/src/main/java/com/wgzhao/addax/plugin/reader/httpreader/HttpReader.java
> [httpreader] Add support for nest path expression

- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/reader/util/GetPrimaryKeyUtil.java
When multiple unique indexes exist, the unique index of the numeric type is automatically selected as the split key
> [addax-rdbms] Auto select numberic type primary key as split key

- plugin/reader/hdfsreader/src/main/java/com/wgzhao/addax/plugin/reader/hdfsreader/DFSUtil.java
- plugin/writer/hdfswriter/src/main/java/com/wgzhao/addax/plugin/writer/hdfswriter/HdfsHelper.java
> [hdfswriter] Fix incorrect store value when use date type with orc file

- common/src/main/java/com/wgzhao/addax/common/element/LongColumn.java
Co-Authored-By: XhivaW <12463092+XhivaW@users.noreply.github.com>
Fix #488
> [addax-common] Fix cast bigint to long error

- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/util/DBUtil.java
> [addax-rdbms] Fix sql exception when set autocommit in clickhouse database

- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/util/DataBaseType.java
- plugin/writer/clickhousewriter/src/main/java/com/wgzhao/addax/plugin/writer/clickhousewriter/ClickHouseWriter.java
- pom.xml
refernces https://github.com/ClickHouse/clickhouse-jdbc/tree/master/clickhouse-jdbc
> Using offical recommended stream writing method to get performs the best

- docs/writer/sqlserverwriter.md
- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/writer/CommonRdbmsWriter.java
- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/writer/util/WriterUtil.java
- plugin/writer/sqlserverwriter/src/main/java/com/wgzhao/addax/plugin/writer/sqlserverwriter/SqlServerWriter.java
> Add support for  mssql merge into statement

- common/src/main/java/com/wgzhao/addax/common/base/Constant.java
- common/src/main/java/com/wgzhao/addax/common/util/EncryptUtil.java
- core/src/main/bin/encrypt_password.sh
- docs/encrypt_password.md
- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/reader/util/OriginalConfPretreatmentUtil.java
- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/writer/util/OriginalConfPretreatmentUtil.java
- mkdocs.yml
- plugin/reader/mongodbreader/src/main/java/com/wgzhao/addax/plugin/reader/mongodbreader/MongoDBReader.java
- plugin/writer/kafkawriter/src/main/java/com/wgzhao/addax/plugin/writer/kafkawriter/KafkaKey.java
- plugin/writer/kafkawriter/src/main/java/com/wgzhao/addax/plugin/writer/kafkawriter/KafkaWriter.java
- plugin/writer/mongodbwriter/src/main/java/com/wgzhao/addax/plugin/writer/mongodbwriter/MongoDBWriter.java
> Add support for encrypt password

- plugin/writer/tdenginewriter/src/main/java/com/wgzhao/addax/plugin/writer/tdenginewriter/ColumnMeta.java
- plugin/writer/tdenginewriter/src/main/java/com/wgzhao/addax/plugin/writer/tdenginewriter/DataHandler.java
- plugin/writer/tdenginewriter/src/main/java/com/wgzhao/addax/plugin/writer/tdenginewriter/DefaultDataHandler.java
- plugin/writer/tdenginewriter/src/main/java/com/wgzhao/addax/plugin/writer/tdenginewriter/OpentsdbDataHandler.java
- plugin/writer/tdenginewriter/src/main/java/com/wgzhao/addax/plugin/writer/tdenginewriter/SchemaManager.java
- plugin/writer/tdenginewriter/src/main/java/com/wgzhao/addax/plugin/writer/tdenginewriter/TDKey.java
- plugin/writer/tdenginewriter/src/main/java/com/wgzhao/addax/plugin/writer/tdenginewriter/TDengineWriter.java
- plugin/writer/tdenginewriter/src/main/java/com/wgzhao/addax/plugin/writer/tdenginewriter/TDengineWriterErrorCode.java
- plugin/writer/tdenginewriter/src/main/java/com/wgzhao/addax/plugin/writer/tdenginewriter/TableMeta.java
- plugin/writer/tdenginewriter/src/main/java/com/wgzhao/addax/plugin/writer/tdenginewriter/TableType.java
- plugin/writer/tdenginewriter/src/main/java/com/wgzhao/addax/plugin/writer/tdenginewriter/TimestampPrecision.java
> Refactor tdenginewriter plugin references offical codes

- plugin/writer/elasticsearchwriter/src/main/java/com/wgzhao/addax/plugin/writer/elasticsearchwriter/ESWriter.java
Fix NPE occurred when read null array type value #611
> Fix NPE occurred when read null array type value #611

- docs/assets/jobs/starrockswriter.json
- 源码中并未有connection这一配置项，已根据[官网](https://docs.starrocks.com/zh-cn/main/loading/DataX-starrocks-writer)做了修改
-
> 修改starrockswriter.json-demo

- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/reader/util/OriginalConfPretreatmentUtil.java
- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/util/DataBaseType.java
- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/util/TableExpandUtil.java
- lib/addax-rdbms/src/main/java/com/wgzhao/addax/rdbms/writer/util/OriginalConfPretreatmentUtil.java
Fix sqlserver table not found when include comma
----
When SQLServer table or columns has special symbol, e.g comma(,), The Table or column's name will truncate to comma
> Fix sqlserver table not found when include comma

- core/src/main/job/stream2databend.json
Add databend config json in core.
> add databend core json

- docs/reader/httpreader.md
- plugin/reader/httpreader/src/main/java/com/wgzhao/addax/plugin/reader/httpreader/HttpKey.java
- plugin/reader/httpreader/src/main/java/com/wgzhao/addax/plugin/reader/httpreader/HttpReader.java
- plugin/reader/httpreader/src/main/resources/plugin_job_template.json
> [feat]Add support for pagination with http reader plugin

- plugin/reader/hivereader/pom.xml
- pom.xml
1. Add missing commons-configuration2 , Jackson-databind and woodstox-core deps
2. downgrade libthrift to 0.13.0 to avoid `java.lang.AbstractMethodError`
> [bugfix][hivereader] Add missing 3rd deps

- docs/setupJob.md
> [improve][docs] correct the description for `speed.channel`

- plugin/writer/hdfswriter/src/main/java/com/wgzhao/addax/plugin/writer/hdfswriter/ParquetWriter.java
Add support for the long type for ParquetWriter
> Add support for the long type for ParquetWriter

- plugin/reader/rdbmsreader/src/main/java/com/wgzhao/addax/plugin/reader/rdbmsreader/RdbmsReader.java
[bugfix][plugin][rdbmsreader]rdbmsreader jdbc_url is string not list
> [bugfix][plugin][rdbmsreader]rdbmsreader jdbc_url is string not list

- plugin/writer/paimonwriter/src/main/java/com/wgzhao/addax/plugin/writer/paimonwriter/PaimonWriter.java
[bugfix][plugin][paimonwriter] write timestamp_ntz data error
> [bugfix][plugin][paimonwriter] write timestamp_ntz data error

- docs/assets/jobs/hdfswriter.json
- docs/writer/hdfswriter.md
- plugin/writer/hdfswriter/src/main/java/com/wgzhao/addax/plugin/writer/hdfswriter/OrcWriter.java
- plugin/writer/hdfswriter/src/main/java/com/wgzhao/addax/plugin/writer/hdfswriter/ParquetWriter.java
- plugin/writer/hdfswriter/src/main/java/com/wgzhao/addax/plugin/writer/hdfswriter/SupportHiveDataType.java
1. Enhance ORC writer to support ARRAY and Map data type
2. Enhance Parquet writer to support ARRAY and Map data type
3. Refactor schema building logic for ORC
> [feature][plugin][hdfswriter] Add support for ARRAY and MAP data type

- plugin/reader/httpreader/pom.xml
- plugin/reader/httpreader/src/main/java/com/wgzhao/addax/plugin/reader/httpreader/HttpKey.java
- plugin/reader/httpreader/src/main/java/com/wgzhao/addax/plugin/reader/httpreader/HttpReader.java
migrate from Apache HttpClient to Java 11 HttpClient
> [refactor][plugin][httpreader] use  Java built-in  HttpClient instead 3rd library

- plugin/writer/excelwriter/src/main/java/com/wgzhao/addax/plugin/writer/excelwriter/ExcelWriter.java
- plugin/writer/excelwriter/src/main/java/com/wgzhao/addax/plugin/writer/excelwriter/SpreadsheetWriter.java
Enhance Excel file write performance by implementing direct XML file generation instead of using standard Excel APIs. This optimization allows for rapid writing of large datasets (100,000+ rows) with significantly improved performance.
Performance improvement:
- Capable of writing 100,000+ rows quickly
- Bypasses overhead of traditional Excel manipulation libraries
- Reduces memory consumption during large dataset operations
> [improve][plugin][excelwriter] Improved Excel write performance by generating XML files directly
